# Generated by Django 5.2.7 on 2025-10-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name='Пользователей всего')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='Создано событий')),
                ('edited_events', models.PositiveIntegerField(default=0, verbose_name='Отредактировано событий')),
                ('cancelled_events', models.PositiveIntegerField(default=0, verbose_name='Отменено событий')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('details', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('tg_user_id', models.BigIntegerField(blank=True, help_text='чтобы потом фильтровать события по конкретному пользователю бота', null=True, verbose_name='ID пользователя Telegram')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
