# Generated by Django 5.2.7 on 2025-10-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='date',
            field=models.DateField(help_text='Статистика за этот день', unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='botstatistics',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пользователей всего (новых за день)'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_tg_id', models.BigIntegerField(db_index=True, verbose_name='Организатор (TG ID)')),
                ('participant_tg_id', models.BigIntegerField(db_index=True, verbose_name='Участник (TG ID)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('declined', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event', models.ForeignKey(blank=True, db_column='event_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendarapp.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-date', '-time', '-id'],
            },
        ),
    ]
