# Generated by Django 5.2.7 on 2025-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_event_options_alter_botstatistics_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='Создано событий (всего)')),
                ('events_edited', models.PositiveIntegerField(default=0, verbose_name='Отредактировано событий (всего)')),
                ('events_cancelled', models.PositiveIntegerField(default=0, verbose_name='Отменено событий (всего)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Пользователь TG',
                'verbose_name_plural': 'Пользователи TG',
                'db_table': 'tg_users',
            },
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
